name: lauzhack_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.4
  injectable: ^2.3.0
  stacked_services: ^1.3.0
  provider: ^6.0.5
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  event_bus: ^2.0.0
  equatable: ^2.0.5
  easy_localization:
  path_provider: ^2.1.1
  hive: ^2.2.3
  http: ^1.1.0
  logger:
  google_fonts:
  flutter_sound: ^9.2.13
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.7
  showcaseview: 2.0.3
  grouped_list: ^5.1.2
  intl:
  sticky_grouped_list: ^3.1.0
  skeletons:
    git:
      url: https://github.com/badjio/skeletons.git
      ref: a0d5b44d3e0c04f587ea3e4997c4a3dfa06677b1
  dropdown_button2: ^2.3.9
  package_info_plus:
  infinite_scroll_pagination: ^4.0.0
  url_launcher: ^6.2.2
  socket_io_client: ^1.0.1
  flutter_staggered_animations:
  visibility_detector:
  cached_network_image:
  flutter_slidable:
  animate_do: ^2.0.0
  mirai:
  flutter_html:
  share_plus: ^7.2.1
  flutter_displaymode:
  file_picker: ^6.1.1
  file_saver: ^0.2.12
  lottie:
  flutter_pdfview: ^1.3.2
  flutter_animate: ^1.0.0
  permission_handler: ^11.3.1
  top_snackbar_flutter: ^3.1.0
  store_redirect: ^2.0.2
  clay_containers:
  win32: ^5.5.3
  archive: ^3.6.1
  glassmorphism: ^3.0.0
  syncfusion_flutter_charts:
  flutter_screenutil:
dev_dependencies:
  build_runner: ^2.4.6
  very_good_analysis: ^5.1.0
  flutter_lints: ^2.0.3
  hive_generator:





flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/cv_edit/
    - assets/svg/stepper/
    - assets/sounds/
    - assets/lottie/
    - assets/lottie/onboarding_en/
    - assets/lottie/onboarding_ar/
    - assets/lottie/ai_assist/

